name: Update Replicas

on:
  workflow_dispatch:

jobs:
  update-replicas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Request Replica Count
        uses: actions/input@v3
        with:
          name: Replica Count
          required: true
          default: 1

      - name: Run update_replicas.py
        run: |
          python replica.py . ${{ inputs.Replica_Count }}  

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update replicaCount in values.yaml files to ${{ inputs.Replica_Count }}"
          git push
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
