name: Update Replicas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-replicas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run update_replicas.py
      run: |
        python replicas.py . 1  # Change to the desired replica count

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update replicaCount in values.yaml files'
        git push
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
